# Config must be compatible with prospector 1.7.7 due to Python 3.6 support.
# Pyright will run in a GitHub workflow as it was added in Prospector 1.10

max-line-length: 120
inherits:
  - strictness_veryhigh

dodgy:
  run: true

mccabe:
  run: true

pycodestyle:
  run: true
  disable:
    # https://github.com/psf/black/issues/354#issuecomment-397685631
    - E203
    - W503
    # Disabled due to the overlap with pylint 
    - E722

pydocstyle:
  run: true
  disable:
    # https://github.com/PyCQA/pydocstyle/issues/627
    - D202
    # https://github.com/PyCQA/pydocstyle/issues/141
    - D203
    # https://github.com/PyCQA/pydocstyle/issues/475
    - D212

pyflakes:
  run: true
  disable:
    - F841 # Covered by pylint

vulture:
  run: true
